### base config ###
# -*- coding: utf-8 -*-

full_field: &FULL_FIELD
  gpu_id: '0,1,2,3' 
  loss: 'l2'
  lr: 1e-3
  max_lr: 1e-3 # 动态学习率, default:1e-3
  min_lr: 1e-5  # 动态学习率
  weight_decay: 0
  factor: 0.8
  patience: 3
  max_epochs: 50
  batch_size: 8
  scheduler: 'ReduceLROnPlateau'
  num_data_workers: 0
  dt: 1                     # how many timesteps ahead the model will predict
  n_history: 0              # how many previous timesteps to consider
  prediction_type: 'iterative'
  prediction_length: 41     # applicable only if prediction_type == 'iterative'
  n_initial_conditions: 5   # applicable only if prediction_type == 'iterative'
  ics_type: "default"       # default or datetime
  date_strings: ["2018-09-15 00:00:00"]
  save_raw_forecasts: !!bool True
  save_channel: !!bool False
  masked_acc: !!bool False
  maskpath: None
  perturb: !!bool False
  add_grid: !!bool False
  N_grid_channels: 0
  gridtype: 'sinusoidal'    # options 'sinusoidal' or 'linear'
  roll: !!bool False
  enable_nhwc: !!bool False
  optimizer_type: 'FusedAdam'

  # directory path to store training checkpoints and other output
  exp_dir: './exp_15_levels_20240828'

  # data
  train_data_path: '/home/data/sample_backbone_04/test'
  valid_data_path: '/home/data/sample_backbone_04/test'  
  test_data_path:  '/home/data/sample_backbone_04/test'
  time_means_path: '/home/data/sample_backbone_04/time_means.npy'

  # land mask
  land_mask: !!bool True
  land_mask_path: '/home/data/sample_backbone_04/land_mask.h5'

  # normalization
  normalize: !!bool True
  normalization: 'zscore' # options zscore, minmax, zscore_lat
  global_mins_path:  '/home/data/sample_backbone_04/global_mins.npy' 
  global_maxs_path:  '/home/data/sample_backbone_04/global_maxs.npy' 
  global_means_path: '/home/data/sample_backbone_04/global_means.npy' 
  global_stds_path:  '/home/data/sample_backbone_04/global_stds.npy' 

  # orography
  orography: !!bool True
  orography_norm_zscore_path: '/home/data/sample_backbone_04/orography_norm_zscore.h5'
  orography_norm_maxmin_path: '/home/data/sample_backbone_04/orography_norm_maxmin.h5'

  # noise
  add_noise: !!bool False
  noise_std: 0

  # crop
  crop_size_x: None
  crop_size_y: None

  log_to_screen: !!bool True
  log_to_wandb: !!bool False
  save_checkpoint: !!bool True
  plot_animations: !!bool False
  
#############################################
afno: &afno
  <<: *FULL_FIELD        # 继承FULL_FIELD锚点中的所有键值对
  nettype: 'afno'
  log_to_wandb: !!bool False

  # afno hyperparams
  num_blocks: 8         # original:8
  patch_size: 8
  width: 56
  modes: 32
  target: 'default'     # options default, residual 

  # Train params
  lr: 1E-3
  batch_size: 32 # 64
  scheduler: 'CosineAnnealingLR'

  # Data params
  fusion_3d_2d: False
  in_channels: [0, 1 ,2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20 ,21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65]
  # in_channels: [0, 1 ,2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20 ,21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71]
  # out_channels: [0, 1 ,2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 66, 67, 68, 69, 70, 71]
  out_channels: [0, 1 ,2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60]
  atmos_channels: [61, 62, 63, 64, 65]
  N_in_channels: 66 
  N_out_channels: 61  
  img_size_h: 720  # not used in afno
  img_size_w: 1440 # not used in afno

  patch_size_h: 8  # not used in afno
  patch_size_w: 8  # not used in afno
  loss_channel_wise: False
  loss_scale: True
  loss_region_weighted: False
#############################################

#############################################
graphcast: &graphcast
  <<: *FULL_FIELD        # 继承FULL_FIELD锚点中的所有键值对
  nettype: 'graphcast'
  log_to_wandb: !!bool False

  # graphcast hyperparams
  num_blocks: 8         # original:8
  patch_size: 8
  width: 56
  modes: 32
  target: 'default'     # options default, residual 

  # Train params
  lr: 1E-3
  batch_size: 32 # 64
  scheduler: 'CosineAnnealingLR'

  # Data params
  fusion_3d_2d: False
  in_channels: [0, 1 ,2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20 ,21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65]
  # in_channels: [0, 1 ,2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20 ,21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71]
  # out_channels: [0, 1 ,2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 66, 67, 68, 69, 70, 71]
  out_channels: [0, 1 ,2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60]
  atmos_channels: [61, 62, 63, 64, 65]
  N_in_channels: 66 
  N_out_channels: 61  
  img_size_h: 720  # not used in afno
  img_size_w: 1440 # not used in afno

  patch_size_h: 8  # not used in afno
  patch_size_w: 8  # not used in afno
  loss_channel_wise: False
  loss_scale: True
  loss_region_weighted: False
#############################################




#############################################
Masked_AE_Ocean: &Masked_AE_Ocean
  <<: *FULL_FIELD
  nettype: 'Masked_AE_Ocean'
  log_to_wandb: !!bool False

  # Train params
  lr: 1E-3
  batch_size: 1
  scheduler: 'CosineAnnealingLR'
  loss_channel_wise: False
  loss_scale: True
  loss_region_weighted: False
  region_idx: [160, 280, 490, 720]
  region_weight: 0.9

  # Data params
  fusion_3d_2d: False 
  # in_chans: 66 
  # out_chans: 61
  atmos_channels: [61, 62, 63, 64, 65]
  # in_channels: [0, 1 ,2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20 ,21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71]
  in_channels: [0, 1 ,2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20 ,21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65]
  # out_channels: [0, 1 ,2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 66, 67, 68, 69, 70, 71]
  out_channels: [0, 1 ,2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60]
  # out_variables: ['t0', 't6', 't10', 't20', 't30', 't50', 't70', 't100', 't125', 't150', 't200', 't250', 't300', 't400', 't500', 's0', 's6', 's10', 's20', 's30', 's50', 's70', 's100', 's125', 's150', 's200', 's250', 's300', 's400', 's500', 'u0', 'u6', 'u10', 'u20', 'u30', 'u50', 'u70', 'u100', 'u125', 'u150', 'u200', 'u250', 'u300', 'u400', 'u500', 'v0', 'v6', 'v10', 'v20', 'v30', 'v50', 'v70', 'v100', 'v125', 'v150', 'v200', 'v250', 'v300', 'v400', 'v500', 'ssh', 'hmax', 'mwd', 'mwp', 'mp1', 'mp2', 'swh']
  out_variables: ['t0', 't6', 't10', 't20', 't30', 't50', 't70', 't100', 't125', 't150', 't200', 't250', 't300', 't400', 't500', 's0', 's6', 's10', 's20', 's30', 's50', 's70', 's100', 's125', 's150', 's200', 's250', 's300', 's400', 's500', 'u0', 'u6', 'u10', 'u20', 'u30', 'u50', 'u70', 'u100', 'u125', 'u150', 'u200', 'u250', 'u300', 'u400', 'u500', 'v0', 'v6', 'v10', 'v20', 'v30', 'v50', 'v70', 'v100', 'v125', 'v150', 'v200', 'v250', 'v300', 'v400', 'v500', 'ssh']
  N_in_channels: 66 # 72
  N_out_channels: 61 # 67  
  img_size_h: 720
  img_size_w: 1440
  patch_size_h: 8
  patch_size_w: 8
  mlp_ratio: 4.

  # Encoder hyperparams
  embed_dim: 512 # 512
  depth: 12  # 16
  num_heads: 16
  # Decoder hyperparams
  decoder_embed_dim: 1024 # 1024 
  decoder_depth: 8
  decoder_num_heads: 16
  # Koopman hyperparams
  koopman_depth: 2
  modes_h_ratio: 1
  modes_w_ratio: 0.8
  # Fourier hyperparams
  drop_rate: 0.
  drop_path_rate: 0.
  sparsity_threshold: 0.01
  hard_thresholding_fraction: 1.0
  num_blocks: 8
